-- MARKET HUB v42 Smart Product Import Suite. Backward-compatible additions only.
create table if not exists product_import_settings (id boolean primary key default true check(id),markup_percent numeric(8,2) not null default 0,fixed_markup_inr numeric(10,2) not null default 0,minimum_profit_inr numeric(10,2) not null default 0,rounding_rule integer not null default 0,default_stock integer not null default 99,default_status text not null default 'draft' check(default_status='draft'),auto_sku boolean not null default true,max_images integer not null default 12,max_media_bytes integer not null default 5242880,allowed_domains text[] not null default '{}'::text[],updated_at timestamptz not null default now());
insert into product_import_settings(id) values(true) on conflict(id) do nothing;
alter table product_import_settings alter column default_stock set default 99;
update product_import_settings set default_stock=99 where default_stock=0;
create table if not exists product_import_jobs (id uuid primary key default gen_random_uuid(),job_type text not null check(job_type in ('single','bulk','extension')),status text not null default 'queued',total_items integer not null default 0,ready_items integer not null default 0,failed_items integer not null default 0,created_by text not null,created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists product_import_items (id uuid primary key default gen_random_uuid(),job_id uuid references product_import_jobs(id) on delete set null,source_url text not null,source_url_hash text not null,source_domain text not null,source_product_id text,source_sku text,title text,normalized_title text,status text not null default 'ready',duplicate_reason text,existing_product_id uuid references products(id),product_data jsonb not null default '{}'::jsonb,error_message text,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table product_import_items add column if not exists published_at timestamptz;
alter table products add column if not exists published_at timestamptz;
alter table products add column if not exists status text not null default 'published';
create index if not exists product_import_items_created on product_import_items(created_at desc);create index if not exists product_import_items_source_hash on product_import_items(source_url_hash);
create table if not exists product_import_media (id uuid primary key default gen_random_uuid(),import_item_id uuid not null references product_import_items(id) on delete cascade,source_url text not null,media_type text not null default 'image',content_type text,file_size integer,width integer,height integer,is_selected boolean not null default true,is_main boolean not null default false,sort_order integer not null default 0,validation_status text not null default 'pending',created_at timestamptz not null default now());
create table if not exists product_import_history (id uuid primary key default gen_random_uuid(),import_item_id uuid references product_import_items(id) on delete set null,product_id uuid references products(id) on delete set null,source_domain text not null,source_url text not null,status text not null,imported_by text not null,error_message text,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());create index if not exists product_import_history_created on product_import_history(created_at desc);
create table if not exists product_source_mappings (id uuid primary key default gen_random_uuid(),source_domain text not null,source_product_id text,source_url_hash text not null,product_id uuid not null references products(id) on delete cascade,created_at timestamptz not null default now(),unique(source_domain,source_url_hash));
create index if not exists product_source_mapping_source_id on product_source_mappings(source_domain,lower(source_product_id)) where source_product_id is not null and source_product_id<>'';
create table if not exists product_import_audit (id uuid primary key default gen_random_uuid(),admin_identity text not null,action text not null,target_id uuid,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());create index if not exists product_import_audit_created on product_import_audit(created_at desc);
create table if not exists product_import_sku_sequence (id bigserial primary key,created_at timestamptz not null default now());
create index if not exists products_import_search_idx on products using gin (to_tsvector('simple'::regconfig,coalesce(name,'')||' '||coalesce(sku,'')||' '||coalesce(description,'')));
create index if not exists products_import_category_idx on products(category_id,is_active,created_at desc);
