'use strict';
const crypto=require('crypto');
const {fetchAuthorizedHtml,validateAuthorizedMedia}=require('./base-importer');
const {extractStructuredProduct}=require('./structured-data');
const {adapterFor}=require('./authorized-source-adapters');
const {normalizeImportedVariants}=require('./variant-normalizer');
const AMAZON_DOMAINS=['amazon.in','amzn.in','media-amazon.com','ssl-images-amazon.com'];
const imageUrl=value=>{try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password?url.href:''}catch{return''}};
function calculatePrice(sourcePrice,settings,override){if(Number.isFinite(Number(override))&&Number(override)>0)return Number(override);const source=Math.max(0,Number(sourcePrice)||0),percent=source*Number(settings.markup_percent||0)/100,fixed=Number(settings.fixed_markup_inr||0),minimum=Number(settings.minimum_profit_inr||0);let price=source+Math.max(minimum,percent+fixed);const rounding=Number(settings.rounding_rule||0);if(rounding===9)price=Math.ceil((price+1)/10)*10-1;else if(rounding===49)price=Math.ceil((price+1)/50)*50-1;else if(rounding===99)price=Math.ceil((price+1)/100)*100-1;return Math.max(0,Math.round(price))}
function effectiveAllowedDomains(url,settings){let host='';try{host=new URL(url).hostname.toLowerCase()}catch{}const configured=settings.allowed_domains||[];return host==='amzn.in'||host==='amazon.in'||host.endsWith('.amazon.in')?[...new Set([...configured,...AMAZON_DOMAINS])]:configured}
function canonicalSourceDomain(value){const host=String(value||'').toLowerCase().replace(/\.$/,'');return host==='amazon.in'||host.endsWith('.amazon.in')?'amazon.in':host}
function normalizeProduct(product,settings){const maxImages=Math.min(20,Math.max(1,Number(settings.max_images||12))),defaultStock=Number(settings.default_stock)>0?Math.floor(Number(settings.default_stock)):99;const images=[...new Set((product.images||[]).map(imageUrl).filter(Boolean))].slice(0,maxImages),variantModel=normalizeImportedVariants(product,defaultStock);return{...product,title:String(product.title||'').slice(0,180),description:String(product.description||'').slice(0,10000),shortDescription:String(product.shortDescription||'').slice(0,500),brand:String(product.brand||'').slice(0,120),category:String(product.category||'').slice(0,120),sku:String(product.sku||'').slice(0,80),stock:defaultStock,images,selectedImages:images,price:product.price==null?null:Number(product.price),mrp:product.mrp==null?null:Number(product.mrp),discount:product.discount==null?null:Number(product.discount),asin:String(product.asin||'').slice(0,10),calculatedPrice:calculatePrice(product.price,settings),sourceUrl:product.sourceUrl,sourceWebsite:product.sourceWebsite,specifications:product.specifications||{},options:variantModel.options,variants:variantModel.variants,tags:Array.isArray(product.tags)?product.tags.slice(0,50):[]}}
async function analyzeUrl(url,settings){const parsed=new URL(url),adapter=adapterFor(parsed.hostname),allowedDomains=effectiveAllowedDomains(url,settings);let product,finalUrl=url;if(adapter){product=await adapter.analyze(url,{settings:{...settings,allowed_domains:allowedDomains}});finalUrl=product.sourceUrl||url}else{const fetched=await fetchAuthorizedHtml(url,{allowedDomains,allowLocal:process.env.NODE_ENV!=='production'});finalUrl=fetched.finalUrl;product=extractStructuredProduct(fetched.html,finalUrl)}if(!product)throw new Error('No JSON-LD Product or usable OpenGraph product data was found.');const normalized=normalizeProduct({...product,sourceUrl:finalUrl,sourceWebsite:canonicalSourceDomain(new URL(finalUrl).hostname)},settings),media=[];for(const candidate of normalized.images){try{media.push(await validateAuthorizedMedia(candidate,{allowedDomains:effectiveAllowedDomains(finalUrl,settings),maxBytes:settings.max_media_bytes,allowLocal:process.env.NODE_ENV!=='production'}))}catch{}}normalized.images=media.map(item=>item.url);normalized.selectedImages=[...normalized.images];normalized.media=media;return normalized}
function sourceHash(url){return crypto.createHash('sha256').update(String(url)).digest('hex')}
async function mapBounded(values,limit,worker){const results=new Array(values.length),queue=[...values.keys()];async function run(){while(queue.length){const index=queue.shift();try{results[index]={status:'ready',value:await worker(values[index],index)}}catch(error){results[index]={status:'failed',error:error.message}}}}await Promise.all(Array.from({length:Math.min(limit,values.length)},run));return results}
module.exports={analyzeUrl,calculatePrice,normalizeProduct,effectiveAllowedDomains,canonicalSourceDomain,sourceHash,mapBounded,AMAZON_DOMAINS};
