'use strict';
const clean=value=>String(value??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const array=value=>Array.isArray(value)?value:value==null?[]:[value];
const number=value=>{const parsed=Number(String(value??'').replace(/[^0-9.]/g,''));return Number.isFinite(parsed)?parsed:null};
function productNodes(value,result=[]){if(Array.isArray(value))value.forEach(item=>productNodes(item,result));else if(value&&typeof value==='object'){const types=array(value['@type']).map(String);if(types.includes('Product'))result.push(value);if(value['@graph'])productNodes(value['@graph'],result)}return result}
function meta(html,key){const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const patterns=[new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']*)["'][^>]*>`,'i'),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${escaped}["'][^>]*>`,'i')];for(const pattern of patterns){const match=html.match(pattern);if(match)return clean(match[1])}return''}
function parseJsonLd(html){const nodes=[];const expression=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let match;while((match=expression.exec(html))){try{productNodes(JSON.parse(match[1].trim()),nodes)}catch{}}return nodes}
function normalize(node,html,sourceUrl){const offers=array(node.offers),offer=offers[0]||{},aggregate=node.aggregateRating||{},brand=typeof node.brand==='object'?node.brand?.name:node.brand;const images=[...new Set(array(node.image).flatMap(item=>typeof item==='object'?[item.url,item.contentUrl]:item).filter(Boolean).map(String))];const variants=array(node.hasVariant).map(item=>({title:clean(item.name),sku:clean(item.sku),color:clean(item.color),size:clean(item.size),price:number(item.offers?.price),availability:clean(item.offers?.availability)}));return{title:clean(node.name||meta(html,'og:title')),shortDescription:clean(meta(html,'og:description')),description:clean(node.description||meta(html,'description')||meta(html,'og:description')),price:number(offer.price||node.price||meta(html,'product:price:amount')),mrp:number(offer.highPrice||node.msrp),brand:clean(brand),category:clean(node.category),sku:clean(node.sku||node.mpn),sourceProductId:clean(node.productID||node.gtin13||node.gtin12||node.gtin8||node.mpn),stock:null,availability:clean(offer.availability),images:images.length?images:[meta(html,'og:image')].filter(Boolean),video:clean(node.video?.contentUrl||node.video?.embedUrl),specifications:node.additionalProperty&&array(node.additionalProperty).reduce((out,item)=>{if(item?.name)out[clean(item.name)]=clean(item.value);return out},{}),features:array(node.features).map(clean).filter(Boolean),color:clean(node.color),size:clean(node.size),variants,tags:[],weight:clean(node.weight?.value||node.weight),dimensions:{width:clean(node.width?.value||node.width),height:clean(node.height?.value||node.height),depth:clean(node.depth?.value||node.depth)},rating:aggregate.ratingValue?{value:number(aggregate.ratingValue),count:number(aggregate.reviewCount||aggregate.ratingCount)}:null,sourceUrl,sourceWebsite:new URL(sourceUrl).hostname}}
function extractStructuredProduct(html,sourceUrl){const nodes=parseJsonLd(html);if(nodes.length)return normalize(nodes[0],html,sourceUrl);const title=meta(html,'og:title'),image=meta(html,'og:image'),price=number(meta(html,'product:price:amount'));if(!title&&!image)return null;return normalize({name:title,image,description:meta(html,'og:description'),offers:{price}},html,sourceUrl)}
module.exports={extractStructuredProduct,parseJsonLd};
