'use strict';

const {fetchAuthorizedHtml}=require('../base-importer');
const {extractStructuredProduct}=require('../structured-data');

const clean=value=>decodeEntities(String(value??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim());
const amount=value=>{const parsed=Number(String(value??'').replace(/[^0-9.]/g,''));return Number.isFinite(parsed)&&parsed>0?parsed:null};
function decodeEntities(value){return value.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,code)=>String.fromCharCode(Number(code)))}
function attribute(tag,name){const match=String(tag||'').match(new RegExp(`\\b${name}=["']([^"']*)["']`,'i'));return match?decodeEntities(match[1]):''}
function elementById(html,id){const escaped=id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),match=html.match(new RegExp(`<([a-z0-9]+)[^>]*\\bid=["']${escaped}["'][^>]*>([\\s\\S]*?)<\\/\\1>`,'i'));return match?clean(match[2]):''}
function amazonAsin(sourceUrl,html=''){let url;try{url=new URL(sourceUrl)}catch{return''}const path=url.pathname.match(/\/(?:dp|gp\/product|gp\/aw\/d)\/([A-Z0-9]{10})(?:[/?]|$)/i),query=url.searchParams.get('asin'),page=String(html).match(/\bdata-asin=["']([A-Z0-9]{10})["']/i);return String(path?.[1]||query||page?.[1]||'').toUpperCase()}
function amazonImages(html){const images=[];const push=value=>{try{const parsed=new URL(decodeEntities(value));if(/^https?:$/.test(parsed.protocol))images.push(parsed.href)}catch{}};for(const match of html.matchAll(/\bdata-old-hires=["']([^"']+)["']/gi))push(match[1]);for(const match of html.matchAll(/\bdata-a-dynamic-image=["']([^"']+)["']/gi)){let value=decodeEntities(match[1]);try{Object.keys(JSON.parse(value)).forEach(push)}catch{}}for(const match of html.matchAll(/<img[^>]+\bid=["']landingImage["'][^>]*>/gi))push(attribute(match[0],'src'));return[...new Set(images)]}
function tableSpecifications(html){const result={};for(const row of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...row[1].matchAll(/<(?:th|td)[^>]*>([\s\S]*?)<\/(?:th|td)>/gi)].map(match=>clean(match[1])).filter(Boolean);if(cells.length>=2&&cells[0].length<=120)result[cells[0]]=cells.slice(1).join(' ')}return result}
function detailSpecifications(html){const result={};for(const item of html.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/gi)){const text=clean(item[1]),separator=text.indexOf(':');if(separator>0&&separator<100){const key=text.slice(0,separator).trim(),value=text.slice(separator+1).trim();if(key&&value)result[key]=value}}return result}
function extractAmazonProduct(html,sourceUrl){const structured=extractStructuredProduct(html,sourceUrl)||{},asin=amazonAsin(sourceUrl,html),title=structured.title||elementById(html,'productTitle'),brand=structured.brand||elementById(html,'bylineInfo').replace(/^(?:Visit the|Brand:)\s*/i,'').replace(/ Store$/i,''),features=elementById(html,'feature-bullets'),description=structured.description||elementById(html,'productDescription')||features,price=structured.price||amount(elementById(html,'priceblock_ourprice')||elementById(html,'priceblock_dealprice')||elementById(html,'corePrice_feature_div')),mrp=structured.mrp||amount(elementById(html,'priceblock_listprice')||elementById(html,'basisPrice')),images=[...new Set([...(structured.images||[]),...amazonImages(html)])],specifications={...(structured.specifications||{}),...tableSpecifications(html),...detailSpecifications(elementById(html,'detailBullets_feature_div'))};if(!title&&!images.length)return null;return{...structured,title,brand,description,shortDescription:structured.shortDescription||features,price,mrp,discount:mrp&&price?Math.max(0,Math.round((mrp-price)*100/mrp)):null,images,specifications,asin,sourceProductId:asin||structured.sourceProductId||'',sourceUrl,sourceWebsite:new URL(sourceUrl).hostname}}
async function analyze(url,{settings}){const allowed=[...(settings.allowed_domains||[]),'amazon.in','amzn.in','media-amazon.com','ssl-images-amazon.com'],fetched=await fetchAuthorizedHtml(url,{allowedDomains:allowed,allowLocal:false}),product=extractAmazonProduct(fetched.html,fetched.finalUrl);if(!product)throw new Error('Amazon did not expose usable public product information for this URL.');return product}

module.exports={analyze,extractAmazonProduct,amazonAsin,amazonImages};
