const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>`₹${Number(v||0).toLocaleString('en-IN')}`,day=v=>v?new Date(v).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—';
let account,orders=[];
async function api(url,options={}){const response=await fetch(url,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json();if(response.status===401)throw Object.assign(new Error('Please sign in.'),{unauthorized:true});if(!response.ok)throw new Error(data.error||'Something went wrong.');return data}
function values(form){return Object.fromEntries(new FormData(form).entries())}function toast(message){const node=$('#accountToast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2500)}
async function start(){try{const data=await api('/api/customer/account');if(!data.authenticated)throw Object.assign(new Error(),{unauthorized:true});account=data.account;$('#customerName').textContent=account.fullName;$('#customerEmail').textContent=account.email;fillProfile();await Promise.all([loadDashboard(),loadOrders()]);showView(location.hash.slice(1)||'dashboard')}catch(error){if(error.unauthorized)location.replace('/login.html?redirect=%2Faccount.html');else toast(error.message)}}
function showView(view){document.querySelectorAll('.account-view').forEach(n=>n.hidden=n.id!==`${view}View`);document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('.account-sidebar').classList.remove('open');history.replaceState(null,'',`#${view}`);if(view==='addresses')loadAddresses();if(view==='wallet')renderWallet();if(view==='coupons')loadCoupons();if(view==='notifications')loadNotifications();if(view==='returns')loadReturns();if(view==='tracking')renderTracking()}
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){e.preventDefault();showView(view.dataset.view)}});
const notesHtml=items=>items.length?items.map(n=>`<article class="notice ${n.isRead?'':'unread'}"><div><b>${esc(n.title)}</b><p>${esc(n.message)}</p></div><small>${day(n.createdAt)}</small></article>`).join(''):'<div class="empty">No notifications yet.</div>';
async function loadDashboard(){const {dashboard:d}=await api('/api/customer/dashboard');$('#summaryCards').innerHTML=[['Total Orders',d.totalOrders],['Pending Orders',d.pendingOrders],['Delivered Orders',d.deliveredOrders],['Wallet Balance',money(d.walletBalance)],['Wishlist',d.wishlistCount],['Unread',d.unreadNotifications]].map(([a,b])=>`<article><small>${a}</small><strong>${b}</strong></article>`).join('');$('#notificationBadge').textContent=d.unreadNotifications||'';$('#recentNotifications').innerHTML=notesHtml(d.recentNotifications)}
async function loadOrders(){({orders}=await api(`/api/customer/orders-v41?status=${encodeURIComponent($('#orderFilter')?.value||'')}`));renderOrders();return orders}
const pics=items=>`<div class="order-pics">${items.slice(0,4).map(i=>`<img loading="lazy" src="${esc(i.image||'assets/favicon.svg')}" alt="${esc(i.name)}">`).join('')}</div>`;
function renderOrders(){const box=$('#ordersList');box.innerHTML=orders.length?orders.map(o=>`<article class="order-card">${pics(o.items)}<div class="order-main"><div><b>Order MH${o.orderNumber}</b><span>${day(o.createdAt)} · ${o.items.length} item(s)</span></div><strong>${money(o.totalInr)}</strong><span class="status">${esc(o.status.replaceAll('_',' '))}</span></div><div class="actions"><a href="order-details.html?order=${o.orderNumber}">View details</a><button data-track>Track order</button><a href="/api/customer/orders/${o.orderNumber}/invoice">Download invoice</a><button data-buy="${o.orderNumber}">Buy again</button>${['pending','confirmed'].includes(o.status)&&!o.awb?`<button class="danger" data-cancel="${o.orderNumber}">Cancel</button>`:''}</div></article>`).join(''):'<div class="empty">No orders found.</div>'}
function renderTracking(){const box=$('#trackingList');box.innerHTML=orders.length?orders.map(o=>`<article class="track-card"><div><b>MH${o.orderNumber}</b><span>${esc(o.courierName||'Courier will be assigned soon')}</span></div><strong>${esc(o.trackingStatus||o.status)}</strong><p>AWB: ${esc(o.awb||'Not assigned')} · Estimated: ${day(o.estimatedDeliveryDate)}</p><a href="order-details.html?order=${o.orderNumber}">View timeline</a></article>`).join(''):'<div class="empty">No orders to track.</div>'}
document.addEventListener('click',async e=>{const cancel=e.target.closest('[data-cancel]'),buy=e.target.closest('[data-buy]');try{if(e.target.closest('[data-track]'))showView('tracking');if(cancel&&confirm('Cancel this order?')){await api(`/api/customer/orders/${cancel.dataset.cancel}/cancel`,{method:'POST'});await Promise.all([loadOrders(),loadDashboard()]);toast('Order cancelled.')}if(buy){const data=await api(`/api/customer/orders/${buy.dataset.buy}/buy-again`,{method:'POST'}),cart=JSON.parse(localStorage.getItem('mh-cart')||'[]');data.items.forEach(item=>{const found=cart.find(x=>String(x.sku)===String(item.sku));found?found.qty=Math.min(99,found.qty+item.qty):cart.push(item)});localStorage.setItem('mh-cart',JSON.stringify(cart));location.href='index.html?cart=open'}}catch(error){toast(error.message)}});$('#orderFilter').onchange=loadOrders;
async function loadAddresses(){const {addresses}=await api('/api/customer/addresses');$('#addressList').innerHTML=addresses.length?addresses.map(a=>`<article class="address">${a.isDefault?'<em>Default</em>':''}<b>${esc(a.label)} · ${esc(a.fullName)}</b><p>${esc(a.line1)} ${esc(a.line2)}, ${esc(a.city)}, ${esc(a.state)} ${esc(a.pincode)}</p><span>${esc(a.phone)}</span><div><button data-edit='${esc(JSON.stringify(a))}'>Edit</button><button data-delete="${a.id}">Delete</button></div></article>`).join(''):'<div class="empty">No saved addresses.</div>'}
$('#addAddressButton').onclick=()=>{$('#addressForm').reset();$('#addressForm').hidden=false};$('#addressForm').onsubmit=async e=>{e.preventDefault();const body=values(e.target);body.isDefault=e.target.isDefault.checked;await api('/api/customer/addresses',{method:'POST',body:JSON.stringify(body)});e.target.hidden=true;loadAddresses();toast('Address saved.')};
document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const a=JSON.parse(edit.dataset.edit),f=$('#addressForm');Object.entries(a).forEach(([k,v])=>{if(f.elements[k])f.elements[k].type==='checkbox'?f.elements[k].checked=v:f.elements[k].value=v??''});f.hidden=false}if(del&&confirm('Delete this address?')){await api(`/api/customer/addresses/${del.dataset.delete}`,{method:'DELETE'});loadAddresses()}})
function renderWallet(){$('#walletSummary').innerHTML=`<article class="wallet"><small>Available balance</small><strong>${money(account.walletBalance)}</strong><span>${account.coinBalance} MARKET HUB Coins</span></article>`;$('#walletHistory').innerHTML=(account.walletActivity||[]).map(x=>`<article class="transaction"><div><b>${esc(x.note||x.type)}</b><small>${day(x.createdAt)}</small></div><strong>${money(x.amount)}</strong></article>`).join('')||'<div class="empty">No wallet transactions.</div>'}
async function loadCoupons(){const {coupons}=await api('/api/customer/coupons');$('#couponList').innerHTML=coupons.map(c=>`<article class="coupon ${c.expired?'expired':''}"><b>${esc(c.code)}</b><strong>${c.type==='percent'?`${c.value}% OFF`:`${money(c.value)} OFF`}</strong><span>Minimum ${money(c.minimumOrderInr)}</span><small>${c.used?'Used':c.expired?'Expired':`Valid until ${day(c.endsAt)}`}</small>${!c.used&&!c.expired?`<button data-coupon="${esc(c.code)}">Apply coupon</button>`:''}</article>`).join('')||'<div class="empty">No coupons available.</div>'}
document.addEventListener('click',e=>{const c=e.target.closest('[data-coupon]');if(c){localStorage.setItem('mh-applied-coupon',c.dataset.coupon);navigator.clipboard?.writeText(c.dataset.coupon);toast('Coupon saved for checkout.')}})
async function loadNotifications(){const {notifications}=await api('/api/customer/notifications');$('#notificationList').innerHTML=notesHtml(notifications)}$('#readAllButton').onclick=async()=>{await api('/api/customer/notifications/read',{method:'POST',body:'{"id":"all"}'});await Promise.all([loadNotifications(),loadDashboard()])};
async function loadReturns(){const {items}=await api('/api/customer/returns');$('#returnList').innerHTML=items.map(i=>`<article class="return"><b>${esc(i.productName)}</b><span>Order MH${i.orderNumber}</span>${i.returnStatus?`<strong>${esc(i.returnStatus)}</strong>`:`<button data-return="${i.orderItemId}">Request return / replacement</button>`}</article>`).join('')||'<div class="empty">No eligible returns.</div>'}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-return]');if(!b)return;const requestType=confirm('OK for replacement, Cancel for return')?'replacement':'return',reason=prompt(`Reason for ${requestType}:`);if(reason)try{await api('/api/customer/returns',{method:'POST',body:JSON.stringify({orderItemId:b.dataset.return,requestType,reason})});loadReturns();toast('Request submitted.')}catch(error){toast(error.message)}})
function fillProfile(){const f=$('#profileForm');['fullName','email','phone','profileImageUrl'].forEach(k=>f.elements[k].value=account[k]||'')}$('#profileForm').onsubmit=async e=>{e.preventDefault();const {profile}=await api('/api/customer/profile',{method:'PUT',body:JSON.stringify(values(e.target))});account={...account,...profile};$('#customerName').textContent=account.fullName;toast('Profile saved.')};$('#passwordForm').onsubmit=async e=>{e.preventDefault();await api('/api/customer/password',{method:'PUT',body:JSON.stringify(values(e.target))});e.target.reset();toast('Password updated.')};
$('#logoutButton').onclick=async()=>{await api('/api/auth/customer/logout',{method:'POST'});location.replace('/')};start();
