'use strict';
const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let currentItem=null,imageState=[],variantEditor=null;

async function api(url,options={}){const response=await fetch(url,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),raw=await response.text();let data;try{data=raw?JSON.parse(raw):{}}catch{data={ok:false,error:{code:'INVALID_SERVER_RESPONSE',message:'The server returned an unreadable response. Please try again.'}}}if(response.status===401){location.href='admin-login.html';throw new Error('Admin sign-in required.')}if(!response.ok){const problem=typeof data.error==='object'?data.error.message:data.error;throw new Error(problem||'The product importer could not complete this request.')}return data}
function toast(message){const node=$('#importToast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2600)}
function setTab(name){document.querySelectorAll('.import-tab').forEach(node=>node.classList.toggle('active',node.id===`${name}Tab`));document.querySelectorAll('[data-tab]').forEach(node=>node.classList.toggle('active',node.dataset.tab===name));if(name==='drafts')loadDrafts();if(name==='history')loadHistory();if(name==='settings')loadSettings()}
function statusRow(item){const review=item.status!=='failed'&&item.status!=='skipped'?`<button data-open-import="${item.id}">Review</button>`:'',publish=item.status==='draft'?`<button class="publish-row" data-open-import="${item.id}" data-focus-publish>Publish Product</button>`:'',view=item.status==='published'&&item.data?.sku?`<a class="view-product" href="product.html?sku=${encodeURIComponent(item.data.sku)}" target="_blank" rel="noopener">View Product</a>`:'';return`<article class="import-row" data-import-row="${item.id}"><div><b>${esc(item.data?.title||item.sourceUrl)}</b><small>${esc(item.sourceDomain)} · ${esc(item.data?.asin||item.data?.sourceProductId||'No source ID')}</small></div><span class="import-status ${esc(item.status)}">${esc(item.status)}</span><div class="import-row-actions">${review}${publish}${view}</div></article>`}

document.addEventListener('click',event=>{const tab=event.target.closest('[data-tab]');if(tab)setTab(tab.dataset.tab);if(event.target.closest('[data-editor-close]'))closeEditor();const open=event.target.closest('[data-open-import]');if(open)openItem(open.dataset.openImport,open.hasAttribute('data-focus-publish'))});

$('#singleImportForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter||event.target.querySelector('button'),url=new FormData(event.target).get('url'),intent=button.dataset.intent||'analyze';event.target.querySelectorAll('button').forEach(node=>node.disabled=true);$('#singleStatus').textContent=intent==='draft'?'Importing available product data as Draft…':'Analyzing available product data…';try{const {item}=await api('/api/admin/product-import/analyze',{method:'POST',body:JSON.stringify({url,intent})});const duplicate=item.status==='duplicate';$('#singleStatus').textContent=duplicate?'Possible duplicate detected. Choose Update Existing, Create New, or Skip.':item.status==='draft'?'Product imported as Draft. Review it before publishing.':'Analysis ready. Review the preview, then save it as Draft.';openEditor(item)}catch(error){$('#singleStatus').textContent=error.message}finally{event.target.querySelectorAll('button').forEach(node=>node.disabled=false)}};
$('#bulkImportForm').onsubmit=async event=>{event.preventDefault();const urls=String(new FormData(event.target).get('urls')||'').split(/\r?\n/).map(value=>value.trim()).filter(Boolean),button=event.target.querySelector('button');button.disabled=true;$('#bulkResults').innerHTML=urls.map(url=>`<article class="import-row"><div><b>${esc(url)}</b></div><span class="import-status">Queued</span></article>`).join('');try{const data=await api('/api/admin/product-import/analyze-bulk',{method:'POST',body:JSON.stringify({urls})});$('#bulkResults').innerHTML=data.items.map(statusRow).join('');const ready=data.items.filter(item=>item.status==='ready');$('#saveAllDrafts').hidden=!ready.length;$('#saveAllDrafts').dataset.ids=ready.map(item=>item.id).join(',')}catch(error){toast(error.message)}finally{button.disabled=false}};
$('#saveAllDrafts').onclick=async event=>{const ids=event.target.dataset.ids.split(',').filter(Boolean);event.target.disabled=true;let saved=0;for(const id of ids)try{const {item}=await api(`/api/admin/product-import/items/${id}`),data=item.data;await api(`/api/admin/product-import/items/${id}`,{method:'PUT',body:JSON.stringify({...data,selectedImages:data.images||[],action:'draft'})});saved++}catch{}toast(`${saved} product${saved===1?'':'s'} saved as Draft.`);event.target.disabled=false;loadDrafts()};

function renderImages(){const holder=$('#editorImages');holder.innerHTML=imageState.length?imageState.map((image,index)=>`<div class="media-row ${image.selected?'':'deselected'}"><input type="checkbox" data-image-select="${index}" ${image.selected?'checked':''} aria-label="Select image ${index+1}"><img loading="lazy" src="${esc(image.url)}" alt="Imported product image ${index+1}"><span>${index===0?'Cover image':`Image ${index+1}`}</span><div><button type="button" data-image-main="${index}" ${index===0?'disabled':''} title="Choose cover image">Cover</button><button type="button" data-image-up="${index}" ${index===0?'disabled':''} aria-label="Move image up">↑</button><button type="button" data-image-down="${index}" ${index===imageState.length-1?'disabled':''} aria-label="Move image down">↓</button><button type="button" data-image-remove="${index}" aria-label="Remove image">×</button></div></div>`).join(''):'<p>Not Available</p>'}
$('#editorImages').onchange=event=>{const select=event.target.closest('[data-image-select]');if(select){imageState[Number(select.dataset.imageSelect)].selected=select.checked;renderImages()}};
$('#editorImages').onclick=event=>{const main=event.target.closest('[data-image-main]'),up=event.target.closest('[data-image-up]'),down=event.target.closest('[data-image-down]'),remove=event.target.closest('[data-image-remove]');if(main){const index=Number(main.dataset.imageMain),chosen=imageState.splice(index,1)[0];chosen.selected=true;imageState.unshift(chosen);renderImages()}else if(up){const index=Number(up.dataset.imageUp);[imageState[index-1],imageState[index]]=[imageState[index],imageState[index-1]];renderImages()}else if(down){const index=Number(down.dataset.imageDown);[imageState[index+1],imageState[index]]=[imageState[index],imageState[index+1]];renderImages()}else if(remove){imageState.splice(Number(remove.dataset.imageRemove),1);renderImages()}};

function setValue(control,value){control.value=value??''}
function openEditor(item){currentItem=item;const data=item.data||{},selected=new Set(data.selectedImages||data.images||[]);imageState=(data.images||data.selectedImages||[]).map(url=>({url,selected:selected.has(url)}));const form=$('#importEditor');setValue(form.title,data.title);setValue(form.shortDescription,data.shortDescription);setValue(form.description,data.description);setValue(form.category,data.marketHubCategory||data.category);setValue(form.brand,data.brand);setValue(form.sku,data.sku);setValue(form.asin,data.asin||data.sourceProductId);setValue(form.mrp,data.mrp);setValue(form.discount,data.discount);setValue(form.sourcePrice,data.price);setValue(form.price,data.calculatedPrice||data.price);setValue(form.stock,data.stock||99);setValue(form.weightGrams,data.weightGrams||data.weight);setValue(form.sourceUrl,item.sourceUrl||data.sourceUrl);form.specifications.value=JSON.stringify(data.specifications||{},null,2);form.tags.value=(data.tags||[]).join(', ');variantEditor=window.MarketHubVariantEditor.mount($('#importVariantEditor'),{options:data.options||[],variants:data.variants||[]},{sku:data.sku||'MH-VAR',price:Number(data.calculatedPrice||data.price)||0,mrp:Number(data.mrp)||null,stock:Number(data.stock)||99,weightGrams:Number(data.weightGrams||data.weight)||500});form.querySelectorAll('[name="duplicateAction"]').forEach(radio=>radio.checked=radio.value===(data.duplicateAction||''));const duplicate=item.status==='duplicate'||Boolean(item.duplicateReason),draft=item.status==='draft',published=item.status==='published',productUrl=published&&data.sku?`product.html?sku=${encodeURIComponent(data.sku)}`:'#';$('#duplicateWarning').hidden=!duplicate;$('#duplicateOptions').hidden=!duplicate;$('#editorStatus').textContent=item.status.toUpperCase();$('#draftBadge').hidden=!draft;$('#saveDraft').hidden=published;$('#publishProduct').hidden=!draft;$('#deleteDraft').hidden=!draft;$('#publishHelp').hidden=draft||published;$('#publishSuccess').hidden=!published;$('#viewPublishedProduct').href=productUrl;renderImages();$('#importEditorBackdrop').hidden=false;document.documentElement.style.overflow='hidden'}
async function openItem(id,focusPublish=false){try{const {item}=await api(`/api/admin/product-import/items/${id}`);openEditor(item);if(focusPublish&&!$('#publishProduct').hidden)$('#publishProduct').focus()}catch(error){toast(error.message)}}
function closeEditor(){$('#importEditorBackdrop').hidden=true;document.documentElement.style.overflow='';currentItem=null;imageState=[];$('#publishSuccess').hidden=true}
function editorData(action){const form=$('#importEditor');let specifications;try{specifications=JSON.parse(form.specifications.value||'{}')}catch{throw new Error('Specifications must contain valid JSON.')}variantEditor.setDefaults({sku:form.sku.value.trim()||'MH-VAR',price:Number(form.price.value)||0,mrp:Number(form.mrp.value)||null,stock:Number(form.stock.value)||99,weightGrams:Number(form.weightGrams.value)||500});const variantData=variantEditor.getValue();return{...currentItem.data,title:form.title.value.trim(),shortDescription:form.shortDescription.value.trim(),description:form.description.value.trim(),category:form.category.value.trim(),brand:form.brand.value.trim(),sku:form.sku.value.trim(),asin:form.asin.value.trim(),sourceProductId:form.asin.value.trim()||currentItem.data?.sourceProductId||'',mrp:Number(form.mrp.value)||null,discount:Number(form.discount.value)||null,price:Number(form.price.value)||null,stock:Number(form.stock.value)||99,weightGrams:Number(form.weightGrams.value)||null,options:variantData.options,variants:variantData.variants,specifications,tags:form.tags.value.split(',').map(value=>value.trim()).filter(Boolean),images:imageState.map(image=>image.url),selectedImages:imageState.filter(image=>image.selected).map(image=>image.url),duplicateAction:new FormData(form).get('duplicateAction')||currentItem.data?.duplicateAction||'',action}}
function setEditorBusy(busy){$('#saveDraft').disabled=busy;$('#publishProduct').disabled=busy;$('#deleteDraft').disabled=busy}
async function saveCurrent(){try{setEditorBusy(true);const payload=editorData('draft'),{result}=await api(`/api/admin/product-import/items/${currentItem.id}`,{method:'PUT',body:JSON.stringify(payload)});currentItem=result;toast('Draft saved.');openEditor(result);loadDrafts();return result}catch(error){toast(error.message)}finally{setEditorBusy(false)}}
function showPublished(result){currentItem={...currentItem,status:'published',publishedAt:result.publishedAt,data:{...currentItem.data,...editorData('publish'),sku:result.product.sku}};$('#editorStatus').textContent='PUBLISHED';$('#draftBadge').hidden=true;$('#saveDraft').hidden=true;$('#publishProduct').hidden=true;$('#deleteDraft').hidden=true;$('#publishHelp').hidden=true;$('#publishSuccess').hidden=false;$('#viewPublishedProduct').href=result.productUrl;toast('Product Published Successfully');loadDrafts()}
async function publishCurrent(){if(currentItem?.status!=='draft')return toast('Save this import as Draft before publishing.');if(!confirm('Publish this reviewed Draft to the live MARKET HUB catalogue?'))return;try{setEditorBusy(true);const payload=editorData('publish'),{result}=await api(`/api/admin/product-import/${currentItem.id}/publish`,{method:'POST',body:JSON.stringify(payload)});showPublished(result)}catch(error){toast(error.message)}finally{setEditorBusy(false)}}
async function deleteCurrent(){if(currentItem?.status!=='draft')return toast('Only Draft products can be deleted here.');if(!confirm('Delete this product Draft? This cannot be undone.'))return;try{setEditorBusy(true);await api(`/api/admin/product-import/${currentItem.id}`,{method:'DELETE'});toast('Draft deleted.');closeEditor();loadDrafts()}catch(error){toast(error.message)}finally{setEditorBusy(false)}}
$('#saveDraft').onclick=saveCurrent;$('#deleteDraft').onclick=deleteCurrent;
$('#importEditor').onsubmit=event=>{event.preventDefault();publishCurrent()};

async function loadDrafts(){try{const data=await api(`/api/admin/product-import/items?status=draft&q=${encodeURIComponent($('#draftSearch').value)}`);$('#draftList').innerHTML=data.items.map(statusRow).join('')||'<p>No import drafts.</p>'}catch(error){toast(error.message)}}
$('#draftSearch').onchange=loadDrafts;
async function loadHistory(){try{const data=await api(`/api/admin/product-import/history?status=${encodeURIComponent($('#historyStatus').value)}&q=${encodeURIComponent($('#historySearch').value)}`);$('#historyList').innerHTML=data.items.map(item=>`<article class="history-row"><div><b>${esc(item.title||'Product import')}</b><small>${new Date(item.created_at).toLocaleString('en-IN')} · ${esc(item.source_domain)}</small></div><span class="import-status ${esc(item.status)}">${esc(item.status)}</span><a href="${esc(item.source_url)}" target="_blank" rel="noopener">Source</a></article>`).join('')||'<p>No import history.</p>'}catch(error){toast(error.message)}}
$('#historyStatus').onchange=loadHistory;$('#historySearch').onchange=loadHistory;
async function loadSettings(){try{const {settings:s}=await api('/api/admin/product-import/settings'),form=$('#importSettings');form.markupPercent.value=s.markup_percent;form.fixedMarkupInr.value=s.fixed_markup_inr;form.minimumProfitInr.value=s.minimum_profit_inr;form.roundingRule.value=s.rounding_rule;form.defaultStock.value=s.default_stock||99;form.maxImages.value=s.max_images;form.maxMediaBytes.value=s.max_media_bytes;form.autoSku.checked=s.auto_sku;form.allowedDomains.value=(s.allowed_domains||[]).join('\n')}catch(error){toast(error.message)}}
$('#importSettings').onsubmit=async event=>{event.preventDefault();const form=event.target,payload={markupPercent:form.markupPercent.value,fixedMarkupInr:form.fixedMarkupInr.value,minimumProfitInr:form.minimumProfitInr.value,roundingRule:form.roundingRule.value,defaultStock:form.defaultStock.value,maxImages:form.maxImages.value,maxMediaBytes:form.maxMediaBytes.value,autoSku:form.autoSku.checked,allowedDomains:form.allowedDomains.value};try{await api('/api/admin/product-import/settings',{method:'PUT',body:JSON.stringify(payload)});toast('Importer settings saved.')}catch(error){toast(error.message)}};

async function init(){try{const products=await api('/api/admin/products'),categories=[...new Set(products.products.map(item=>item.category).filter(Boolean))].sort();$('#categoryOptions').innerHTML=categories.map(value=>`<option value="${esc(value)}">`).join('');await loadSettings();const params=new URLSearchParams(location.search),source=params.get('url');if(source){setTab('single');$('#singleImportForm').url.value=source;$('#singleStatus').textContent='Review this link, then Analyze or Import as Draft. Nothing publishes automatically.'}}catch(error){toast(error.message)}}
init();
