// Smart discovery is transparent, first-party ranking; no external AI service.
const {database}=require('./db');let schemaReady;const cache=new Map();const key=v=>/^[A-Za-z0-9_-]{16,80}$/.test(String(v||''))?String(v):null;const uuid=v=>/^[0-9a-f-]{36}$/i.test(String(v||''))?String(v):null;const limit=v=>Math.max(1,Math.min(12,Number(v)||6));
async function schema(){if(schemaReady)return schemaReady;schemaReady=(async()=>{const db=database();await db.query(`create table if not exists discovery_search_events(id bigserial primary key,user_id uuid references users(id) on delete set null,session_id varchar(80),query varchar(120) not null,result_count integer not null default 0,clicked_sku varchar(100),created_at timestamptz not null default now(),check(user_id is not null or session_id is not null))`);await db.query('create index if not exists discovery_search_query_recent on discovery_search_events(query,created_at desc)');await db.query('create index if not exists discovery_search_created on discovery_search_events(created_at desc)');return true})();return schemaReady}
const fields=`select p.id,p.sku,p.name,p.slug,p.description,p.specifications,p.price_inr,p.compare_at_price_inr,p.stock_quantity,coalesce(c.name,'Uncategorized') category,coalesce((select pi.url from product_images pi where pi.product_id=p.id order by pi.sort_order limit 1),'') image_url from products p left join categories c on c.id=p.category_id`;
const map=r=>({id:r.id,sku:r.sku,name:r.name,slug:r.slug,description:r.description||'',price_inr:Number(r.price_inr),compare_at_price_inr:r.compare_at_price_inr==null?null:Number(r.compare_at_price_inr),stock_quantity:Number(r.stock_quantity),category:r.category,image_url:r.image_url,gallery:r.image_url?[r.image_url]:[],specifications:r.specifications||{}});
async function search(query,amount=6){const q=String(query||'').trim().slice(0,100);if(q.length<2)return {products:[],categories:[],brands:[],suggestion:null};const saved=cache.get(q.toLowerCase());if(saved&&saved.until>Date.now())return saved.value;const like='%'+q.replace(/[\\%_]/g,'\\$&')+'%',starts=q+'%';const r=await database().query(`${fields} where p.is_active and p.stock_quantity>0 and (p.name ilike $1 escape '\\' or p.sku ilike $1 escape '\\' or c.name ilike $1 escape '\\') order by case when lower(p.sku)=lower($2) then 0 when lower(p.name)=lower($2) then 1 when lower(p.name) like lower($3) then 2 when lower(c.name)=lower($2) then 3 else 4 end,p.created_at desc limit $4`,[like,q,starts,limit(amount)]);const products=r.rows.map(map),categories=[...new Set(products.map(p=>p.category))].slice(0,5);const value={products,categories,brands:[],suggestion:null};cache.set(q.toLowerCase(),{until:Date.now()+30_000,value});return value}
async function recordSearch(input){await schema();const q=String(input.query||'').trim().slice(0,120);if(q.length<2)return {recorded:false};const userId=uuid(input.userId),sessionId=key(input.sessionId);if(!userId&&!sessionId)return {recorded:false};const count=Math.max(0,Math.min(1000,Number(input.resultCount)||0)),clicked=String(input.clickedSku||'').trim().slice(0,100)||null;const seen=await database().query(`select id from discovery_search_events where coalesce(user_id::text,'')=coalesce($1,'') and coalesce(session_id,'')=coalesce($2,'') and query=$3 and created_at>now()-interval '60 seconds' limit 1`,[userId,sessionId,q]);if(seen.rowCount)return {recorded:false};await database().query('insert into discovery_search_events(user_id,session_id,query,result_count,clicked_sku) values($1,$2,$3,$4,$5)',[userId,sessionId,q,count,clicked]);return {recorded:true}}
async function compare(skus){const values=[...new Set((Array.isArray(skus)?skus:[]).map(x=>String(x).trim()).filter(Boolean))].slice(0,4);if(values.length<2)throw new Error('Choose at least two products to compare.');const r=await database().query(`${fields} where p.is_active and p.sku=any($1::text[])`,[values]);return {products:values.map(s=>r.rows.find(x=>x.sku===s)).filter(Boolean).map(map)}}
async function analytics(){await schema();const db=database(),q=async sql=>(await db.query(sql)).rows;return {topSearches:await q(`select query,count(*)::integer total from discovery_search_events where created_at>now()-interval '30 days' group by query order by total desc limit 8`),zeroResults:await q(`select query,count(*)::integer total from discovery_search_events where result_count=0 and created_at>now()-interval '30 days' group by query order by total desc limit 8`),searchCtr:await q(`select count(*) filter(where clicked_sku is not null)::integer clicks,count(*)::integer searches from discovery_search_events where created_at>now()-interval '30 days'`)}}
module.exports={schema,search,recordSearch,compare,analytics};
