// Omnichannel foundation: no external connector calls run without a separately configured private credential vault.
const { database } = require('./db');
const CHANNELS=['website','amazon','flipkart','meesho','myntra','ajio'], modes=new Set(['sandbox','production']); let ready;
const clean=v=>String(v||'').trim();
async function schema(){if(ready)return ready;ready=(async()=>{const db=database();await db.query(`create table if not exists sales_channels(id uuid primary key default gen_random_uuid(),channel_key varchar(32) unique not null,display_name varchar(80) not null,is_enabled boolean not null default false,connection_status varchar(24) not null default 'not_connected',environment varchar(16) not null default 'sandbox',last_sync_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`);await db.query(`create table if not exists channel_sync_jobs(id bigserial primary key,channel_key varchar(32) not null,scope varchar(32) not null,mode varchar(16) not null default 'dry_run',status varchar(24) not null default 'blocked',summary jsonb not null default '{}'::jsonb,created_at timestamptz not null default now())`);await db.query(`create table if not exists marketplace_mappings(id uuid primary key default gen_random_uuid(),channel_key varchar(32) not null,product_id uuid,sku varchar(120),category_mapping varchar(200),attribute_mapping jsonb not null default '{}'::jsonb,status varchar(24) not null default 'unmapped',updated_at timestamptz not null default now(),unique(channel_key,sku))`);await db.query(`create table if not exists channel_inventory(id bigserial primary key,channel_key varchar(32) not null,product_id uuid,available_stock integer not null default 0,reserved_stock integer not null default 0,safety_stock integer not null default 0,updated_at timestamptz not null default now(),unique(channel_key,product_id))`);await db.query(`create table if not exists channel_prices(id bigserial primary key,channel_key varchar(32) not null,product_id uuid,price_inr numeric(12,2),sale_price_inr numeric(12,2),minimum_price_inr numeric(12,2),maximum_price_inr numeric(12,2),updated_at timestamptz not null default now(),unique(channel_key,product_id))`);await db.query('create index if not exists channel_sync_jobs_channel_recent on channel_sync_jobs(channel_key,created_at desc)');await db.query('create index if not exists marketplace_mappings_channel_status on marketplace_mappings(channel_key,status)');await db.query('create index if not exists channel_inventory_channel_stock on channel_inventory(channel_key,available_stock)');await Promise.all(CHANNELS.map(k=>db.query(`insert into sales_channels(channel_key,display_name) values($1,$2) on conflict(channel_key) do nothing`,[k,k==='website'?'MARKET HUB Website':k[0].toUpperCase()+k.slice(1)])));return true})();return ready}
async function channels(){await schema();return(await database().query(`select channel_key,display_name,is_enabled,connection_status,environment,last_sync_at,updated_at from sales_channels order by case when channel_key='website' then 0 else 1 end,display_name`)).rows}
async function status(key){await schema();if(!CHANNELS.includes(key))throw Error('Unknown sales channel.');return(await database().query(`select channel_key,display_name,is_enabled,connection_status,environment,last_sync_at from sales_channels where channel_key=$1`,[key])).rows[0]}
async function configure(input){await schema();const key=clean(input.channel),environment=clean(input.environment||'sandbox');if(!CHANNELS.includes(key)||key==='website'||!modes.has(environment))throw Error('Choose a valid marketplace and environment.');const r=await database().query(`update sales_channels set environment=$2,is_enabled=false,connection_status='not_connected',updated_at=now() where channel_key=$1 returning channel_key,display_name,is_enabled,connection_status,environment`,[key,environment]);return {...r.rows[0],message:'Connection is ready for private credential setup. Sync remains disabled until a secure connector is configured.'}}
async function inventory(){await schema();const r=await database().query(`select p.id,p.sku,p.name,p.stock_quantity as website_stock,coalesce(sum(ci.reserved_stock),0)::integer as reserved_stock,coalesce(sum(ci.available_stock),0)::integer as marketplace_stock from products p left join channel_inventory ci on ci.product_id=p.id where p.is_active=true group by p.id order by p.stock_quantity asc,p.name limit 250`);return r.rows}
async function analytics(){await schema();const db=database(),[c,j,i]=await Promise.all([db.query(`select connection_status,count(*)::integer total from sales_channels group by connection_status`),db.query(`select status,count(*)::integer total from channel_sync_jobs group by status`),db.query(`select count(*) filter(where stock_quantity<=0)::integer out_of_stock,count(*) filter(where stock_quantity between 1 and 9)::integer low_stock,count(*)::integer total from products where is_active=true`)]);return {channels:c.rows,jobs:j.rows,inventory:i.rows[0],note:'External channel data is unavailable until each marketplace connector is securely configured.'}}
async function requestSync(input){await schema();const key=clean(input.channel),scope=clean(input.scope||'products');if(!CHANNELS.includes(key)||key==='website')throw Error('Choose a marketplace connector.');const channel=await status(key);const valid=['products','inventory','pricing','images','descriptions','all'].includes(scope)?scope:'products';const r=await database().query(`insert into channel_sync_jobs(channel_key,scope,mode,status,summary) values($1,$2,'dry_run','blocked',$3::jsonb) returning id,channel_key,scope,mode,status,created_at`,[key,valid,JSON.stringify({reason:channel.connection_status==='connected'?'Connector execution is not enabled in this release.':'Marketplace is not connected. No external call was made.'})]);return {...r.rows[0],message:'Dry-run saved. No marketplace data was changed.'}}
module.exports={schema,channels,status,configure,inventory,analytics,requestSync};
