// First-party marketing foundation. Provider delivery is intentionally disabled until configured privately.
const {database}=require('./db');let ready;const types=new Set(['email','banner','announcement','coupon','flash_sale','product_promotion']),states=new Set(['draft','scheduled','running','paused','completed','archived']);
async function schema(){if(ready)return ready;ready=(async()=>{const db=database();await db.query(`create table if not exists marketing_campaigns(id uuid primary key default gen_random_uuid(),name varchar(160) not null,campaign_type varchar(40) not null,status varchar(30) not null default 'draft',audience varchar(80) not null default 'all',content jsonb not null default '{}'::jsonb,start_at timestamptz,end_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`);await db.query(`create table if not exists marketing_banners(id uuid primary key default gen_random_uuid(),title varchar(160) not null,subtitle varchar(240),image_url text,cta_label varchar(80),destination_url text,placement varchar(60) not null default 'homepage',priority integer not null default 0,is_enabled boolean not null default false,start_at timestamptz,end_at timestamptz,created_at timestamptz not null default now())`);await db.query(`create table if not exists marketing_events(id bigserial primary key,campaign_id uuid references marketing_campaigns(id) on delete set null,event_type varchar(40) not null,created_at timestamptz not null default now())`);await db.query(`create table if not exists marketing_automation_jobs(id bigserial primary key,job_type varchar(60) not null,payload jsonb not null default '{}'::jsonb,status varchar(30) not null default 'queued',run_at timestamptz not null default now(),created_at timestamptz not null default now())`);await db.query('create index if not exists marketing_campaign_status_start on marketing_campaigns(status,start_at)');await db.query('create index if not exists marketing_banner_enabled_priority on marketing_banners(is_enabled,priority)');await db.query('create index if not exists marketing_events_campaign_recent on marketing_events(campaign_id,created_at desc)');return true})();return ready}
const clean=v=>String(v||'').trim();function campaignInput(x){const name=clean(x.name).slice(0,160),type=clean(x.type),status=clean(x.status||'draft'),audience=clean(x.audience||'all').slice(0,80);if(!name||!types.has(type)||!states.has(status))throw new Error('Enter a campaign name, type and valid status.');return {name,type,status,audience,content:typeof x.content==='object'?x.content:{},startAt:x.startAt||null,endAt:x.endAt||null}}
async function campaigns(){await schema();const r=await database().query(`select id,name,campaign_type,status,audience,start_at,end_at,created_at,updated_at from marketing_campaigns order by created_at desc limit 250`);return r.rows}
async function saveCampaign(x){await schema();const v=campaignInput(x),r=await database().query(`insert into marketing_campaigns(name,campaign_type,status,audience,content,start_at,end_at) values($1,$2,$3,$4,$5::jsonb,$6,$7) returning id,name,campaign_type,status,audience,start_at,end_at,created_at`,[v.name,v.type,v.status,v.audience,JSON.stringify(v.content),v.startAt,v.endAt]);return r.rows[0]}
async function banners(){await schema();const r=await database().query(`select id,title,subtitle,image_url,cta_label,destination_url,placement,priority,is_enabled,start_at,end_at,created_at from marketing_banners order by priority desc,created_at desc limit 100`);return r.rows}
async function overview(){await schema();const db=database(),[c,b,e,j]=await Promise.all([db.query(`select status,count(*)::integer total from marketing_campaigns group by status`),db.query('select count(*) filter(where is_enabled)::integer live,count(*)::integer total from marketing_banners'),db.query(`select event_type,count(*)::integer total from marketing_events where created_at>now()-interval '30 days' group by event_type`),db.query(`select count(*) filter(where status='queued')::integer queued,count(*) filter(where status='failed')::integer failed from marketing_automation_jobs`)]);return {campaigns:c.rows,banners:b.rows[0],events:e.rows,jobs:j.rows[0],providerStatus:'disabled',note:'Email and push providers are disabled until private provider credentials are configured.'}}
async function assistant(){const o=await overview(),running=o.campaigns.find(x=>x.status==='running')?.total||0;return {suggestions:[running?`${running} campaign${running===1?' is':'s are'} currently running.`:'Create a draft campaign before scheduling a promotion.',o.banners.live?`${o.banners.live} banner${o.banners.live===1?' is':'s are'} enabled.`:'No banners are enabled yet.',o.jobs.failed?`${o.jobs.failed} automation job${o.jobs.failed===1?' requires':'s require'} review.`:'No failed automation jobs.'],providerStatus:o.providerStatus}}
module.exports={schema,campaigns,saveCampaign,banners,overview,assistant};
