// Rule-based, first-party recommendation adapter. No external AI provider is used.
const { database }=require('./db');let ready;const types=new Set(['product_viewed','cart_added','wishlist_added','search_submitted','recommendation_clicked','category_viewed','product_purchased']);
const session=v=>/^[A-Za-z0-9_-]{16,80}$/.test(String(v||''))?String(v):null;const id=v=>/^[0-9a-f-]{36}$/i.test(String(v||''))?String(v):null;const lim=v=>Math.max(1,Math.min(12,Number(v)||8));
async function schema(){if(ready)return ready;ready=(async()=>{const db=database();await db.query(`create table if not exists shopping_activity_events(id bigserial primary key,user_id uuid references users(id) on delete set null,session_id varchar(80),product_id uuid references products(id) on delete set null,category varchar(100),event_type varchar(40) not null,search_term varchar(120),placement varchar(80),created_at timestamptz not null default now(),check(user_id is not null or session_id is not null))`);await db.query('create index if not exists activity_product_recent on shopping_activity_events(product_id,created_at desc)');await db.query('create index if not exists activity_user_recent on shopping_activity_events(user_id,created_at desc) where user_id is not null');await db.query('create index if not exists activity_session_recent on shopping_activity_events(session_id,created_at desc) where session_id is not null');return true})();return ready}
const fields=`select p.id,p.sku,p.name,p.slug,p.description,p.price_inr,p.compare_at_price_inr,p.stock_quantity,coalesce(c.name,'Uncategorized') category,coalesce((select pi.url from product_images pi where pi.product_id=p.id order by pi.sort_order limit 1),'') image_url from products p left join categories c on c.id=p.category_id`;
const map=r=>({id:r.id,sku:r.sku,name:r.name,slug:r.slug,description:r.description||'',price_inr:Number(r.price_inr),compare_at_price_inr:r.compare_at_price_inr==null?null:Number(r.compare_at_price_inr),stock_quantity:Number(r.stock_quantity),category:r.category,image_url:r.image_url,gallery:r.image_url?[r.image_url]:[]});
async function track(x){await schema();const type=String(x.type||'');if(!types.has(type))throw new Error('Unsupported activity event.');const userId=id(x.userId),sessionId=session(x.sessionId);if(!userId&&!sessionId)throw new Error('A valid session is required.');const productId=id(x.productId),category=String(x.category||'').trim().slice(0,100)||null,term=String(x.searchTerm||'').trim().slice(0,120)||null,placement=String(x.placement||'').trim().slice(0,80)||null;const db=database(),seen=await db.query(`select id from shopping_activity_events where coalesce(user_id::text,'')=coalesce($1,'') and coalesce(session_id,'')=coalesce($2,'') and coalesce(product_id::text,'')=coalesce($3,'') and event_type=$4 and created_at>now()-interval '90 seconds' limit 1`,[userId,sessionId,productId,type]);if(seen.rowCount)return {recorded:false};await db.query('insert into shopping_activity_events(user_id,session_id,product_id,category,event_type,search_term,placement) values($1,$2,$3,$4,$5,$6,$7)',[userId,sessionId,productId,category,type,term,placement]);if(Math.random()<.01)db.query("delete from shopping_activity_events where created_at<now()-interval '90 days'").catch(()=>{});return {recorded:true}}
async function recent(identity,limit=8){await schema();const key=identity.userId?id(identity.userId):session(identity.sessionId);if(!key)return [];const col=identity.userId?'user_id':'session_id',r=await database().query(`${fields} join (select product_id,max(created_at) t from shopping_activity_events where ${col}=$1 and event_type='product_viewed' and product_id is not null group by product_id) a on a.product_id=p.id where p.is_active and p.status='published' and coalesce(p.specifications->>'gift_only','false') <> 'true' and p.stock_quantity>0 order by a.t desc limit $2`,[key,lim(limit)]);return r.rows.map(map)}
async function fresh(limit=8){const r=await database().query(`${fields} where p.is_active and p.status='published' and coalesce(p.specifications->>'gift_only','false') <> 'true' and p.stock_quantity>0 order by p.created_at desc limit $1`,[lim(limit)]);return r.rows.map(map)}
async function trending(limit=8){await schema();const r=await database().query(`${fields} join (select product_id,sum((case event_type when 'product_purchased' then 10 when 'cart_added' then 4 when 'wishlist_added' then 3 when 'product_viewed' then 1 else 0 end)*exp(-extract(epoch from now()-created_at)/604800)) score from shopping_activity_events where product_id is not null and created_at>now()-interval '30 days' group by product_id) a on a.product_id=p.id where p.is_active and p.status='published' and coalesce(p.specifications->>'gift_only','false') <> 'true' and p.stock_quantity>0 order by a.score desc limit $1`,[lim(limit)]);return r.rows.map(map)}
async function best(limit=8){const r=await database().query(`${fields} join (select oi.product_id,sum(oi.quantity) q from order_items oi join orders o on o.id=oi.order_id where oi.product_id is not null and o.payment_status<>'failed' and o.status not in('cancelled','refunded','returned') group by oi.product_id) a on a.product_id=p.id where p.is_active and p.status='published' and coalesce(p.specifications->>'gift_only','false') <> 'true' and p.stock_quantity>0 order by a.q desc limit $1`,[lim(limit)]);return r.rows.map(map)}
async function home(identity={},limit=8){const [rv,tr,bs,nw]=await Promise.all([recent(identity,limit),trending(limit),best(limit),fresh(limit)]);let rec=bs.length?bs:tr.length?tr:nw;if(identity.userId||identity.sessionId){await schema();const key=identity.userId?id(identity.userId):session(identity.sessionId),col=identity.userId?'user_id':'session_id';if(key){const a=await database().query(`select category from shopping_activity_events where ${col}=$1 and category is not null order by created_at desc limit 1`,[key]);if(a.rowCount){const r=await database().query(`${fields} where p.is_active and p.status='published' and coalesce(p.specifications->>'gift_only','false') <> 'true' and p.stock_quantity>0 and c.name=$1 order by p.created_at desc limit $2`,[a.rows[0].category,lim(limit)]);if(r.rowCount)rec=r.rows.map(map)}}}return {continueShopping:rv,recommended:rec,trending:tr.length?tr:nw,bestSellers:bs.length?bs:nw,newArrivals:nw,recentlyViewed:rv}}
async function product(sku,identity={},limit=6){const c=await database().query('select id,category_id,price_inr from products where sku=$1 and is_active',[String(sku||'')]);if(!c.rowCount)return null;const x=c.rows[0],r=await database().query(`${fields} where p.is_active and p.status='published' and coalesce(p.specifications->>'gift_only','false') <> 'true' and p.stock_quantity>0 and p.id<>$1 and (p.category_id=$2 or p.price_inr between $3 and $4) order by abs(p.price_inr-$5),p.created_at desc limit $6`,[x.id,x.category_id,Number(x.price_inr)*.65,Number(x.price_inr)*1.35,Number(x.price_inr),lim(limit)]);return {similar:r.rows.map(map),frequentlyBoughtTogether:[],pairedFallback:'Pairs well with',recentlyViewed:await recent(identity,limit),alternatives:r.rows.map(map).slice(0,4)}}
async function admin(){await schema();const metric=async t=>(await database().query(`select p.sku,p.name,count(*)::integer total from shopping_activity_events e join products p on p.id=e.product_id where e.event_type=$1 group by p.sku,p.name order by total desc limit 8`,[t])).rows;return {mostViewed:await metric('product_viewed'),mostWishlisted:await metric('wishlist_added'),mostAddedToCart:await metric('cart_added'),recommendationClicks:await metric('recommendation_clicked'),trending:await trending(8),bestSellers:await best(8)}}
module.exports={schema,track,home,product,recent,admin};
