document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="site-fix.css"><link rel="stylesheet" href="poster-fix.css">');
let products = [
  {id:1,name:'NovaPods Pro Wireless Earbuds',cat:'Electronics',price:899,old:1499,off:'40% OFF',rating:'4.7 (328)',bulk:'Buy 3+ at ₹799',img:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=500&q=80'},
  {id:2,name:'Stainless Steel Insulated Bottle',cat:'Home & Kitchen',price:349,old:599,off:'42% OFF',rating:'4.8 (1.2k)',bulk:'Buy 4+ at ₹299',img:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=500&q=80'},
  {id:3,name:'Urban Classic Cotton T-Shirt',cat:'Men’s Fashion',price:399,old:799,off:'50% OFF',rating:'4.6 (892)',bulk:'Buy 5+ at ₹329',img:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=500&q=80'},
  {id:4,name:'GlowCo Daily Skincare Set',cat:'Beauty',price:649,old:999,off:'35% OFF',rating:'4.9 (640)',bulk:'Buy 3+ at ₹549',img:'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=80'},
  {id:5,name:'Halo Smart Watch Series 8',cat:'Smart Devices',price:1799,old:2999,off:'40% OFF',rating:'4.7 (2.1k)',bulk:'Buy 2+ at ₹1,599',img:'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=500&q=80'},
  {id:6,name:'Soft-Touch Kitchen Towels, Set of 4',cat:'Home & Kitchen',price:299,old:499,off:'40% OFF',rating:'4.8 (511)',bulk:'Buy 5+ at ₹249',img:'https://images.unsplash.com/photo-1583845112203-454c8d51b4e4?auto=format&fit=crop&w=500&q=80'},
  {id:7,name:'FlexFit Active Sneakers',cat:'Shoes',price:999,old:1599,off:'38% OFF',rating:'4.5 (711)',bulk:'Buy 2+ at ₹899',img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80'},
  {id:8,name:'Lumina Desk Lamp',cat:'Home Decor',price:799,old:1299,off:'38% OFF',rating:'4.7 (287)',bulk:'Buy 3+ at ₹699',img:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=500&q=80'}
];
const categories=[['📱','Mobiles'],['🎧','Electronics'],['👕','Fashion'],['💄','Beauty'],['🪑','Home & Living'],['🍳','Kitchen'],['🏋️','Sports & Fitness'],['🎮','Gaming'],['🧸','Toys & Baby'],['🛒','Groceries'],['⌚','Watches'],['🎁','Gift items'],['🐾','Pet supplies'],['📚','Books & Office'],['🚗','Automotive'],['⚙️','Tools & Hardware']];
let cart=JSON.parse(localStorage.getItem('mh-cart')||'[]');let wishes=JSON.parse(localStorage.getItem('mh-wishes')||'[]');
const money=n=>'₹'+n.toLocaleString('en-IN');
function productUrl(p){return p.sku?`product.html?sku=${encodeURIComponent(p.sku)}`:`product.html?id=${p.id}`}
function card(p){const coins=Math.floor(p.price/100)*10;const url=productUrl(p);return `<article class="product-card"><a class="product-open" href="${url}" aria-label="View ${p.name}"><div class="product-image"><img loading="lazy" src="${p.img}" alt="${p.name}">${p.off?`<span class="discount">${p.off}</span>`:''}</div></a><button class="wish ${wishes.includes(p.id)?'active':''}" aria-label="Save ${p.name}" data-wish="${p.id}">${wishes.includes(p.id)?'♥':'♡'}</button><div class="product-info"><span class="category-label">${p.cat}</span><h3 title="${p.name}"><a href="${url}">${p.name}</a></h3><div class="rating">★★★★★ <span>${p.rating}</span></div><div class="prices"><b>${money(p.price)}</b>${p.old?`<del>${money(p.old)}</del>`:''}</div><span class="bulk">${p.bulk}</span><span class="coins">✦ Earn ${coins} coins</span><button class="share" title="Share product" aria-label="Share ${p.name}" data-share="${p.id}">↗</button><button class="add" aria-label="Add ${p.name} to cart" data-add="${p.id}">+</button></div></article>`}
document.getElementById('categoryGrid').innerHTML=categories.map(c=>`<a class="category" href="shop.html?q=${encodeURIComponent(c[1])}" aria-label="Shop ${c[1]}"><span class="cat-img">${c[0]}</span><b>${c[1]}</b></a>`).join('');
function renderProductGrids(){document.getElementById('dealGrid').innerHTML=products.slice(0,4).map(card).join('');document.getElementById('trendGrid').innerHTML=products.slice(4,10).map(card).join('');document.getElementById('newGrid').innerHTML=products.slice(10,14).map(card).join('');}
renderProductGrids();
async function loadPdfStorefrontCatalogue(){try{const response=await fetch('assets/catalogue/products.json',{cache:'no-store'});if(!response.ok)return;const pdfProducts=await response.json();const selected=[];const usedCategories=new Set();for(const item of pdfProducts){if(!usedCategories.has(item.category)){usedCategories.add(item.category);selected.push(item)}if(selected.length===14)break}const selectedCodes=new Set(selected.map(item=>item.sku));for(const item of pdfProducts){if(selected.length===14)break;if(!selectedCodes.has(item.sku)){selectedCodes.add(item.sku);selected.push(item)}}const liveProducts=pdfProducts.map(item=>({id:10000+item.id,sku:item.sku,name:item.name,cat:item.category,price:item.price_inr,rating:'New catalogue item',bulk:`Wholesale price · ${item.stock_quantity} in stock`,img:item.image_url}));const featured=selected.map(item=>liveProducts.find(product=>product.id===10000+item.id));products=[...featured,...liveProducts.filter(product=>!featured.some(item=>item.id===product.id))];renderProductGrids()}catch(error){console.warn('PDF catalogue preview could not load.',error)}}
loadPdfStorefrontCatalogue();
function updateCart(){localStorage.setItem('mh-cart',JSON.stringify(cart));localStorage.setItem('mh-wishes',JSON.stringify(wishes));document.getElementById('cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0);document.getElementById('wishCount').textContent=wishes.length;document.getElementById('cartSubtotal').textContent=money(cart.reduce((n,x)=>n+x.price*x.qty,0));document.getElementById('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><img src="${x.img}" alt="${x.name}"><div><h4>${x.name}</h4><p>${money(x.price)} × ${x.qty}</p></div><button data-remove="${x.id}" aria-label="Remove ${x.name}">Remove</button></div>`).join(''):'<p class="empty-state">Your cart is waiting for something good.</p>'}
function toast(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2700)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');const wish=e.target.closest('[data-wish]');const remove=e.target.closest('[data-remove]');const share=e.target.closest('[data-share]');const message=e.target.closest('[data-toast]');if(add){const p=products.find(x=>x.id===+add.dataset.add);const existing=cart.find(x=>x.id===p.id);existing?existing.qty++:cart.push({...p,qty:1});updateCart();toast(`${p.name} added to cart`)}if(wish){const id=+wish.dataset.wish;wishes=wishes.includes(id)?wishes.filter(x=>x!==id):[...wishes,id];updateCart();document.querySelectorAll(`[data-wish="${id}"]`).forEach(b=>{b.classList.toggle('active',wishes.includes(id));b.textContent=wishes.includes(id)?'♥':'♡'});toast(wishes.includes(id)?'Saved to your wishlist':'Removed from your wishlist')}if(share){const p=products.find(x=>x.id===+share.dataset.share);const text=`Shop ${p.name} on MARKET HUB`;navigator.share?navigator.share({title:'MARKET HUB',text,url:location.href}):navigator.clipboard?.writeText(`${text} ${location.href}`).then(()=>toast('Product link copied — share it with friends!'))}if(remove){cart=cart.filter(x=>x.id!==+remove.dataset.remove);updateCart();toast('Removed from your cart')}if(message)toast(message.dataset.toast)});
const drawer=document.getElementById('cartDrawer'),backdrop=document.getElementById('drawerBackdrop');function setDrawer(open){drawer.classList.toggle('open',open);backdrop.classList.toggle('show',open);drawer.setAttribute('aria-hidden',!open)}document.getElementById('cartButton').onclick=()=>setDrawer(true);document.querySelector('.close-drawer').onclick=()=>setDrawer(false);backdrop.onclick=()=>setDrawer(false);document.getElementById('wishlistButton').onclick=()=>toast(wishes.length?`${wishes.length} saved product${wishes.length>1?'s':''} in your wishlist.`:'Your wishlist is empty.');
async function beginShiprocketCheckout(event){
  if(!cart.length)return toast('Add an item before checking out.');
  const checkoutButton=document.getElementById('checkoutButton');checkoutButton.disabled=true;checkoutButton.textContent='Opening secure checkout…';
  try{
    const configResponse=await fetch('/api/config/shiprocket-checkout',{cache:'no-store'});
    const config=await configResponse.json().catch(()=>({}));
    if(!configResponse.ok)throw new Error(config.error||'Checkout settings could not be checked. Please try again.');
    if(!config.ready)throw new Error('Shiprocket Checkout is not connected yet.');
    if(!window.HeadlessCheckout||typeof window.HeadlessCheckout.addToCart!=='function')throw new Error('Secure checkout could not load. Please refresh and try again.');
    const response=await fetch('/api/checkout/shiprocket/access-token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cart:cart.map(item=>({sku:item.sku,qty:item.qty}))})});
    const checkout=await response.json().catch(()=>({}));if(!response.ok)throw new Error(checkout.error||'Shiprocket Checkout could not start. Your cart is still saved.');
    if(!checkout.token)throw new Error('Shiprocket Checkout did not return a secure checkout link. Your cart is still saved.');
    window.HeadlessCheckout.addToCart(event,checkout.token,{fallbackUrl:`${location.origin}/shop.html`});
  }catch(error){toast(error.message||'Secure checkout could not start. Your cart is still saved.');}
  finally{checkoutButton.disabled=false;checkoutButton.textContent='Checkout securely →';}
}
document.getElementById('checkoutButton').onclick=beginShiprocketCheckout;
const input=document.getElementById('searchInput'),suggestions=document.getElementById('suggestions');function search(){const q=input.value.trim().toLowerCase();if(!q)return toast('Try a product, brand or category.');const found=products.filter(p=>(p.name+p.cat).toLowerCase().includes(q));toast(found.length?`${found.length} matching product${found.length>1?'s':''} found.`:'No exact matches yet — try a broader search.');suggestions.classList.remove('show')}input.addEventListener('input',()=>{const q=input.value.toLowerCase();const found=q?products.filter(p=>(p.name+p.cat).toLowerCase().includes(q)).slice(0,4):[];suggestions.innerHTML=found.map(p=>`<button data-search="${p.name}">⌕&nbsp;&nbsp;${p.name}</button>`).join('');suggestions.classList.toggle('show',!!found.length)});suggestions.onclick=e=>{const button=e.target.closest('[data-search]');if(button){input.value=button.dataset.search;search()}};document.getElementById('searchButton').onclick=search;input.addEventListener('keydown',e=>e.key==='Enter'&&search());
document.getElementById('voiceSearch').onclick=()=>{if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window))return toast('Voice search is not supported in this browser.');const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;const recognition=new Speech();recognition.lang='en-IN';recognition.onresult=e=>{input.value=e.results[0][0].transcript;search()};recognition.start();toast('Listening… say what you are looking for.');};document.getElementById('allCategories').onclick=()=>document.getElementById('categories').scrollIntoView();document.getElementById('newsletterForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('You’re on the MARKET HUB list — welcome!')};
document.getElementById('photoSearch').onchange=e=>{if(e.target.files?.[0])toast('Photo selected. Visual product matching will activate when the secure image-search service is connected.');};
let remaining=10*3600+34*60+22;setInterval(()=>{remaining--;const h=String(Math.floor(remaining/3600)).padStart(2,'0'),m=String(Math.floor(remaining%3600/60)).padStart(2,'0'),s=String(remaining%60).padStart(2,'0');document.getElementById('timer').textContent=`${h} : ${m} : ${s}`},1000);updateCart();

// Reliable shared shopping controls.
function openShopSearch(){const value=input.value.trim();if(!value)return toast('Try a product, brand or category.');location.href=`shop.html?q=${encodeURIComponent(value)}`}
document.getElementById('searchButton').onclick=openShopSearch;input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();openShopSearch()}});
suggestions.onclick=event=>{const button=event.target.closest('[data-search]');if(button){input.value=button.dataset.search;openShopSearch()}};
document.addEventListener('click',event=>{const remove=event.target.closest('[data-remove]');if(!remove)return;const id=String(remove.dataset.remove);cart=cart.filter(item=>String(item.id||item.sku)!==id);updateCart();});
const whatsapp=document.querySelector('.whatsapp');whatsapp.onclick=event=>{event.stopPropagation();window.open('https://wa.me/919726281287?text='+encodeURIComponent('Hello MARKET HUB, I need help with my order.'),'_blank','noopener')};
const photoInput=document.getElementById('photoSearch');photoInput.setAttribute('capture','environment');photoInput.onchange=event=>{const photo=event.target.files?.[0];if(!photo)return;const reader=new FileReader();reader.onload=()=>{document.querySelector('.photo-preview')?.remove();const preview=document.createElement('aside');preview.className='photo-preview';preview.innerHTML=`<img src="${reader.result}" alt="Selected product photo"><b>Photo selected</b><button>Browse matching products</button>`;preview.querySelector('button').onclick=()=>location.href='shop.html';document.body.append(preview);toast('Photo selected. Choose a product category to continue.');};reader.readAsDataURL(photo)};
function showWelcome(){if(localStorage.getItem('mh-welcome-seen'))return;const modal=document.createElement('section');modal.className='welcome-screen';modal.innerHTML='<div class="welcome-card"><img class="welcome-logo" src="assets/market-hub-logo.png" alt="MARKET HUB"><h2>Welcome to MARKET HUB</h2><p>Sign in for rewards, wallet refunds and faster checkout — or continue shopping as a guest.</p><div class="welcome-actions"><a href="account.html">Sign in</a><a class="welcome-create" href="account.html?mode=register">Create account</a><button class="welcome-skip">Continue as guest</button></div></div>';modal.querySelector('.welcome-skip').onclick=()=>{localStorage.setItem('mh-welcome-seen','1');modal.remove()};document.body.append(modal)}
showWelcome();
const offer=document.getElementById('wholesale');if(offer)offer.innerHTML='<article class="tumbler-offer"><div class="tumbler-copy"><p>MARKET HUB OFFER</p><h2>Free premium<br>tumbler</h2><span>On orders above ₹999</span></div><img src="free-tumbler-offer.png" alt="Free premium tumbler on orders above ₹999"><a href="shop.html">Shop now →</a></article>';
async function requireCustomerBeforeCheckout(event){if(!cart.length)return toast('Add an item before checking out.');try{const response=await fetch('/api/customer/account',{cache:'no-store'});const data=await response.json();if(data.authenticated)return beginShiprocketCheckout(event)}catch{}toast('Please sign in or create an account before checkout.');setTimeout(()=>location.href='account.html?return=checkout',700)}
document.getElementById('checkoutButton').onclick=requireCustomerBeforeCheckout;
if(new URLSearchParams(location.search).get('cart')==='open')setDrawer(true);
// v27 smart cart: it uses the same local MARKET HUB cart and the unchanged
// Shiprocket access-token endpoint.  Nothing is copied into a second cart.
function updateCart(){localStorage.setItem('mh-cart',JSON.stringify(cart));localStorage.setItem('mh-wishes',JSON.stringify(wishes));const count=cart.reduce((n,x)=>n+Math.max(1,Number(x.qty||1)),0);document.getElementById('cartCount').textContent=count;document.getElementById('wishCount').textContent=wishes.length;const subtotal=cart.reduce((n,x)=>n+Number(x.price||0)*Math.max(1,Number(x.qty||1)),0);document.getElementById('cartSubtotal').textContent=money(subtotal);const offerRemaining=Math.max(0,999-subtotal);document.getElementById('cartItems').innerHTML=cart.length?`${cart.map((x,index)=>`<div class="cart-row smart-cart-row"><img src="${x.img||'assets/market-hub-logo.png'}" alt="${String(x.name||'Product').replace(/"/g,'&quot;')}"><div><h4>${x.name}</h4><p>${money(x.price)} each</p><div class="cart-quantity"><button data-cart-delta="-1" data-cart-key="${String(x.sku||x.id)}" aria-label="Decrease quantity">−</button><b>${Math.max(1,Number(x.qty||1))}</b><button data-cart-delta="1" data-cart-key="${String(x.sku||x.id)}" aria-label="Increase quantity">+</button></div></div><button data-smart-remove="${String(x.sku||x.id)}" aria-label="Remove ${String(x.name||'product').replace(/"/g,'&quot;')}">Remove</button></div>`).join('')}<aside class="smart-cart-summary"><b>${offerRemaining?`Add ${money(offerRemaining)} more for your free premium tumbler`:'Free premium tumbler added to your order'}</b><span>Delivery availability is checked securely by Shiprocket at checkout.</span><label>Delivery pincode <input id="cartPincode" inputmode="numeric" maxlength="6" placeholder="Enter pincode"></label><button id="cartDeliveryCheck" type="button">Check delivery</button><p id="cartDeliveryResult">${localStorage.getItem('mh-delivery-pincode')?'Check updated delivery estimate.':'Enter pincode to check delivery.'}</p></aside>`:'<p class="empty-state">Your cart is waiting for something good.</p>';const pin=document.getElementById('cartPincode');if(pin)pin.value=localStorage.getItem('mh-delivery-pincode')||'';document.getElementById('cartDeliveryCheck')?.addEventListener('click',async()=>{const pincode=(pin.value||'').replace(/\D/g,'').slice(0,6),result=document.getElementById('cartDeliveryResult');if(!/^\d{6}$/.test(pincode)){result.textContent='Enter a valid 6-digit pincode.';return;}result.textContent='Checking delivery…';try{const response=await fetch(`/api/shipping/estimate?pincode=${encodeURIComponent(pincode)}`),data=await response.json();result.textContent=data.serviceable===true?(data.estimatedDeliveryDate?`Estimated delivery by ${new Date(`${data.estimatedDeliveryDate}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}.`:data.message):data.message||'This pincode is not serviceable.';localStorage.setItem('mh-delivery-pincode',pincode);}catch{result.textContent='Delivery estimate is temporarily unavailable. Shiprocket Checkout will confirm options.';}})}
document.addEventListener('click',event=>{const quantity=event.target.closest('[data-cart-delta]'),remove=event.target.closest('[data-smart-remove]');if(quantity){const row=cart.find(item=>String(item.sku||item.id)===quantity.dataset.cartKey);if(row){row.qty=Math.max(1,Math.min(99,Number(row.qty||1)+Number(quantity.dataset.cartDelta)));updateCart();}}if(remove){cart=cart.filter(item=>String(item.sku||item.id)!==remove.dataset.smartRemove);updateCart();toast('Removed from your cart');}});
updateCart();
// v30 premium layer is loaded after the existing cart and Shiprocket checkout logic.
// premium-v30.js is loaded once directly by index.html. Do not inject a second copy.
