'use strict';
const assert=require('assert'),http=require('http');
const {extractStructuredProduct}=require('../importers/structured-data');
const {extractAmazonProduct,amazonAsin}=require('../importers/authorized-source-adapters/amazon');
const {validateImportUrl,fetchAuthorizedHtml,validateAuthorizedMedia}=require('../importers/base-importer');
const {analyzeUrl,calculatePrice,normalizeProduct,effectiveAllowedDomains,canonicalSourceDomain,mapBounded}=require('../importers/import-service');
const product={"@context":"https://schema.org","@type":"Product","name":"Controlled Test Shoe","description":"Authorized controlled fixture","image":["http://127.0.0.1:43242/image.jpg","http://127.0.0.1:43242/image-2.webp"],"brand":{"name":"Fixture Brand"},"category":"Test Footwear","offers":{"@type":"Offer","price":"500","availability":"https://schema.org/InStock"},"hasVariant":[{"@type":"Product","name":"Blue / 8","color":"Blue","size":"8"}]};
const html=`<!doctype html><script type="application/ld+json">${JSON.stringify(product)}</script>`;
const amazonHtml=`<!doctype html><html><head><meta property="og:image" content="https://m.media-amazon.com/images/I/cover.jpg"></head><body><span id="productTitle">Fixture Amazon Bottle</span><a id="bylineInfo">Visit the Fixture Brand Store</a><div id="feature-bullets"><ul><li><span>Steel insulated bottle</span></li></ul></div><div id="corePrice_feature_div"><span>₹1,299.00</span></div><span id="basisPrice">₹1,999.00</span><img id="landingImage" src="https://m.media-amazon.com/images/I/main.jpg" data-a-dynamic-image='{&quot;https://m.media-amazon.com/images/I/main.jpg&quot;:[1000,1000],&quot;https://m.media-amazon.com/images/I/side.jpg&quot;:[1000,1000]}'><table><tr><th>Material</th><td>Stainless Steel</td></tr></table></body></html>`;
async function rejects(action,pattern){let message='';try{await action()}catch(error){message=error.message}assert.match(message,pattern)}
(async()=>{const parsed=extractStructuredProduct(html,'https://authorized.example/product/1');assert.equal(parsed.title,'Controlled Test Shoe');assert.equal(parsed.price,500);assert.equal(parsed.images.length,2);assert.equal(parsed.variants.length,1);assert.equal(parsed.sku,'');const amazon=extractAmazonProduct(amazonHtml,'https://www.amazon.in/dp/B0ABC12345');assert.equal(amazon.title,'Fixture Amazon Bottle');assert.equal(amazon.brand,'Fixture Brand');assert.equal(amazon.asin,'B0ABC12345');assert.equal(amazon.sourceProductId,'B0ABC12345');assert.equal(amazon.price,1299);assert.equal(amazon.mrp,1999);assert.equal(amazon.images.length,3);assert.equal(amazon.specifications.Material,'Stainless Steel');assert.equal(amazonAsin('https://www.amazon.in/gp/product/B0ABC12345?ref=x'),'B0ABC12345');assert.equal(canonicalSourceDomain('www.amazon.in'),'amazon.in');assert.equal(normalizeProduct({title:'Stock Fixture',images:[]},{default_stock:0,max_images:12}).stock,99);assert.equal(normalizeProduct({title:'Stock Fixture',images:[]},{default_stock:25,max_images:12}).stock,25);assert(effectiveAllowedDomains('https://www.amazon.in/dp/B0ABC12345',{allowed_domains:[]}).includes('media-amazon.com'));assert.equal(calculatePrice(500,{markup_percent:20,fixed_markup_inr:0,minimum_profit_inr:0,rounding_rule:0}),600);assert.equal(calculatePrice(587,{markup_percent:0,fixed_markup_inr:0,minimum_profit_inr:0,rounding_rule:99}),599);await rejects(()=>validateImportUrl('file:///etc/passwd'),/HTTPS/);await rejects(()=>validateImportUrl('javascript:alert(1)'),/HTTPS/);await rejects(()=>validateImportUrl('data:text/html,x'),/HTTPS/);await rejects(()=>validateImportUrl('https://127.0.0.1/product'),/Private/);await rejects(()=>validateImportUrl('https://169.254.169.254/latest/meta-data'),/Private/);await rejects(()=>validateImportUrl('https://example.com/product',['supplier.example']),/authorized-source/);
  const server=http.createServer((req,res)=>{if(req.url==='/large'){res.writeHead(200,{'Content-Type':'text/html'});return res.end('x'.repeat(2*1024*1024+1))}if(req.url==='/bad.svg'){res.writeHead(200,{'Content-Type':'image/svg+xml','Content-Length':'20'});return req.method==='HEAD'?res.end():res.end('<svg></svg>')}if(req.url==='/head-block.jpg'&&req.method==='HEAD'){res.writeHead(405);return res.end()}if(req.url.endsWith('.jpg')){res.writeHead(200,{'Content-Type':'image/jpeg','Content-Length':'100'});return res.end()}if(req.url.endsWith('.webp')){res.writeHead(200,{'Content-Type':'image/webp','Content-Length':'100'});return res.end()}res.writeHead(200,{'Content-Type':'text/html'});res.end(html)});await new Promise(resolve=>server.listen(43242,'127.0.0.1',resolve));try{const fetched=await fetchAuthorizedHtml('http://127.0.0.1:43242/product',{allowLocal:true});assert.match(fetched.html,/Controlled Test Shoe/);await rejects(()=>fetchAuthorizedHtml('http://127.0.0.1:43242/large',{allowLocal:true}),/2 MB/);await rejects(()=>validateAuthorizedMedia('http://127.0.0.1:43242/bad.svg',{allowLocal:true}),/allowed raster/);assert.equal((await validateAuthorizedMedia('http://127.0.0.1:43242/head-block.jpg',{allowLocal:true,maxBytes:1000})).contentType,'image/jpeg');const analyzed=await analyzeUrl('http://127.0.0.1:43242/product',{allowed_domains:['127.0.0.1'],markup_percent:20,fixed_markup_inr:0,minimum_profit_inr:0,rounding_rule:0,default_stock:0,max_images:12,max_media_bytes:1000});assert.equal(analyzed.calculatedPrice,600);assert.equal(analyzed.stock,99);assert.equal(analyzed.images.length,2);let active=0,maximum=0;const bulk=await mapBounded([1,2,3,4,5],3,async value=>{active++;maximum=Math.max(maximum,active);await new Promise(resolve=>setTimeout(resolve,10));active--;return value});assert.equal(bulk.length,5);assert(maximum<=3)}finally{server.close()}console.log('product-import tests passed')})().catch(error=>{console.error(error);process.exitCode=1});
