const assert=require('assert/strict');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const db=fs.readFileSync(path.join(root,'db.js'),'utf8');
const html=fs.readFileSync(path.join(root,'admin-import.html'),'utf8');
const ui=fs.readFileSync(path.join(root,'admin-import.js'),'utf8');
const migration=fs.readFileSync(path.join(root,'database','v42-product-import.sql'),'utf8');
const storefront=fs.readFileSync(path.join(root,'storefront-v40.js'),'utf8');
const productPage=fs.readFileSync(path.join(root,'product.js'),'utf8');
const shop=fs.readFileSync(path.join(root,'shop.js'),'utf8');
const wishlist=fs.readFileSync(path.join(root,'wishlist-v29.js'),'utf8');
const home=fs.readFileSync(path.join(root,'home-v40.js'),'utf8');

assert(server.includes("const publishImportRoute=url.pathname.match(/^\\/api\\/admin\\/product-import\\/([0-9a-f-]{36})\\/publish$/i)"),'dedicated publish route is missing');
assert.match(server,/publishImportRoute&&req\.method==='POST'/);
assert.match(server,/deleteImportRoute&&req\.method==='DELETE'/);
assert.match(db,/select \* from product_import_items where id=\$1 for update/,'publish must lock the draft');
assert.match(db,/row\.status==='published'&&row\.existing_product_id/,'repeated publish must return the existing product');
assert.match(db,/status='published',published_at=coalesce\(published_at,now\(\)\)/);
assert.match(db,/insert into product_images\(product_id,url,alt_text,sort_order\)/);
assert.match(db,/product_import_audit[\s\S]*'published'/);
assert.match(db,/compare_at_price_inr/);
assert.match(db,/variants:Array\.isArray\(data\.variants\)/);
assert.match(db,/draft_deleted/);
assert.match(migration,/products_import_search_idx/);
assert.match(migration,/products_import_category_idx/);
assert.match(migration,/product_import_items add column if not exists published_at/);
assert.match(html,/id="saveDraft"[^>]*>Save Draft/);
assert.match(html,/id="publishProduct"[^>]*>Publish Product/);
assert.match(html,/id="deleteDraft"[^>]*>Delete Draft/);
assert.match(html,/Product Published Successfully/);
assert.match(html,/id="viewPublishedProduct"[^>]*>View Product/);
assert.match(ui,/\/api\/admin\/product-import\/\$\{currentItem\.id\}\/publish/);
assert.match(ui,/toast\('Product Published Successfully'\)/);
assert.match(ui,/loadDrafts\(\)/);
assert.match(ui,/data-focus-publish/);
assert.match(db,/where p\.is_active = true/);
assert.match(server,/if \(query\) products = products\.filter/);
assert.match(server,/if \(category\) products = products\.filter/);
assert.match(storefront,/data-mh-add-to-cart/);
assert.match(storefront,/data-mh-wishlist-toggle/);
assert.match(productPage,/product\.html\?sku|fetchProducts\(\{ page: 1/);
assert.match(shop,/store\.fetchProducts\(\{page,limit,q:state\.query,category:state\.category/);
assert.match(wishlist,/store\.fetchProducts\(\{page:1,limit:1,q:sku/);
assert.match(home,/loadPage:\(page,limit\)=>store\.fetchProducts/);
console.log('product-import publish workflow tests passed');
